### ISSUE TITLE
Fix .travis.yml

### ISSUE THREAD

**Issue by Mithgol** [mapbox/node-get#10]
A couple of problems in `.travis.yml`:
1. Node.js version `0.4` is not available on Travis CI, and the latest stable version (v0.10.12) is used instead of it in testing ([example](https://travis-ci.org/developmentseed/node-get/jobs/11440572)). This line should be removed.
2. Version `0.10` should be quoted (`"0.10"`), otherwise this YML value is treated as float and converted to 0.1. That's how it appears in a job list ([example](https://travis-ci.org/developmentseed/node-get/builds/11440571)).

**Comment by springmeyer** [comment]
Thanks for catching these problems. Happy to accept a pull fixing this.

**Comment by Mithgol** [comment]
A pull is requested: #11.
